joints:
  - left_hand_synergy_joint
  - left_hand_thumb_abd_joint
  - left_hand_thumb_inner_joint
  - left_hand_thumb_outer_joint
  - left_hand_index_abd_joint
  - left_hand_index_inner_joint
  - left_hand_index_middle_joint
  - left_hand_index_outer_joint
  - left_hand_middle_abd_joint
  - left_hand_middle_inner_joint
  - left_hand_middle_middle_joint
  - left_hand_middle_outer_joint
  - left_hand_ring_abd_joint
  - left_hand_ring_inner_joint
  - left_hand_ring_middle_joint
  - left_hand_ring_outer_joint
  - left_hand_little_abd_joint
  - left_hand_little_inner_joint
  - left_hand_little_middle_joint
  - left_hand_little_outer_joint
  - left_hand_thumb_inner_joint_mimic
  - left_hand_thumb_outer_joint_mimic
  - left_hand_index_inner_joint_mimic
  - left_hand_index_middle_joint_mimic
  - left_hand_index_outer_joint_mimic
  - left_hand_middle_inner_joint_mimic
  - left_hand_middle_middle_joint_mimic
  - left_hand_middle_outer_joint_mimic
  - left_hand_ring_middle_joint_mimic
  - left_hand_ring_inner_joint_mimic
  - left_hand_ring_outer_joint_mimic
  - left_hand_little_inner_joint_mimic
  - left_hand_little_middle_joint_mimic
  - left_hand_little_outer_joint_mimic